spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: enrollment-service
              uri: http://localhost:8001
              predicates:
                - Path=/enrollment/**        # incoming path on gateway
              filters:
                - StripPrefix=1              # /enrollment/api/v1/... -> /api/v1/...

            - id: sftp-service
              uri: http://localhost:8002
              predicates:
                - Path=/sftp/**              # incoming path on gateway
              filters:
                - StripPrefix=1


